### ISSUE TITLE
ergo-graphql fails to build

### ISSUE THREAD

**Issue by reqlez** [abchrisxyz/ergo-setup#12]
ergo-graphql fails to build:

Even after i set the ergo-graphql to latest version, it was failing to build for me. I tried to adjust some settings, and could not make it work ( mind you, i did not spend a lot of time on it ). I went ahead and pre-installed the node modules and uploaded into my own repo to make this work: https://github.com/reqlez/ergo-graphql

This might be an upstream issue?

**Comment by abchrisxyz** [comment]
Builds fine on my side. How did it fail?

**Comment by reqlez** [comment]
Of course i'm testing it again, and it's building fine... It was one of the modules it had issues getting ( could not resolve i think? ).

Confirmed now it's okay!
